//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlienciSTP.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public string Comments { get; set; }
        public int NextInspectionYears { get; set; }
        public Nullable<System.DateTime> Notified { get; set; }
        public string NotificationComments { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
